### PR TITLE
Postandpatch

### PR DESCRIPTION
**Pull request by jeffrey20122021**

### CODE REVIEW

**Review by holgiosalos — COMMENTED** [review]
This PR just should contains changes over test/GithubApi.Issue.test.js file, other files contains same changes than previous PRs #6 and #7. Please merge main/master with this branch to reflect last changes on that branch :)

**Comment by jeffrey20122021** [comment]
> 

done @holgiosalos

**Comment by jeffrey20122021** [comment]
done

**Comment by holgiosalos** [comment]
If i look at the commits I don't see any merge commit from master:
image

For previous PR, the commits history reflect a merge commit from master:
image

When you create several PRs, you need to update the existing PRs with the latest changes on master/main branch each time a PR is approved and merged to the master/main branch.

**Comment by jeffrey20122021** [comment]
> If i look at the commits I don't see any merge commit from master: image
> 
> For previous PR, the commits history reflect a merge commit from master: image
> 
> When you create several PRs, you need to update the existing PRs with the latest changes on master/main branch each time a PR is approved and merged to the master/main branch.



> If i look at the commits I don't see any merge commit from master: image
> 
> For previous PR, the commits history reflect a merge commit from master: image
> 
> When you create several PRs, you need to update the existing PRs with the latest changes on master/main branch each time a PR is approved and merged to the master/main branch.

I did the changes again
image
@holgiosalos

**Comment by holgiosalos** [comment]
@jeffrey20122021 push them :)

**Comment by jeffrey20122021** [comment]
> @jeffrey20122021 push them :)

already push it @holgiosalos

**Comment by holgiosalos** [comment]
@jeffrey20122021 for future pull requests apply the same process, this PR just got updated to me, don't know why

**Review by holgiosalos — APPROVED** [review]

**Pull request merged**
